//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividades
    {
        public Nullable<int> CveAct { get; set; }
        public string DescAct { get; set; }
        public int Genera_Visita { get; set; }
        public Nullable<bool> Incluye_Compromiso { get; set; }
        public Nullable<bool> Incluye_Archivo { get; set; }
        public Nullable<bool> Incluye_Monto { get; set; }
    }
}
