//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivxOp
    {
        public Nullable<int> CveOport { get; set; }
        public int CveAct { get; set; }
        public Nullable<int> tipoact { get; set; }
        public string respact { get; set; }
        public string Descact { get; set; }
        public Nullable<System.DateTime> fechaact { get; set; }
        public string status { get; set; }
        public string contactoAct { get; set; }
        public Nullable<int> cveEtapa { get; set; }
        public string UsResp { get; set; }
        public Nullable<System.DateTime> FechaCompromiso { get; set; }
        public Nullable<System.DateTime> FechaRegAct { get; set; }
        public string usuRegAct { get; set; }
        public Nullable<int> Act_Comp { get; set; }
        public string Nombre_Act_Comp { get; set; }
        public int Status_Comp { get; set; }
        public Nullable<System.DateTime> Fecha_Comp_Ori { get; set; }
        public int CveContacto { get; set; }
        public Nullable<bool> Incluye_Archivo { get; set; }
        public Nullable<bool> ActPreventa { get; set; }
        public Nullable<double> Tiempo { get; set; }
        public Nullable<bool> ActCont { get; set; }
        public Nullable<int> Tecnologia { get; set; }
        public Nullable<int> Clasificador { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> TipoHoras { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public Nullable<int> Tipo_Act_Comp { get; set; }
        public Nullable<int> IdCompromiso { get; set; }
        public Nullable<double> CostoAdicional { get; set; }
        public Nullable<double> CostoTerceros { get; set; }
        public Nullable<double> CostoViaticos { get; set; }
    }
}
