//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicacionesPermiso
    {
        public int id_Permiso { get; set; }
        public Nullable<bool> Permiso { get; set; }
        public string Login { get; set; }
        public Nullable<System.DateTime> Fecha_Permiso { get; set; }
        public Nullable<int> NumAplicacion { get; set; }
    
        public virtual Aplicaciones Aplicaciones { get; set; }
    }
}
