//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avances
    {
        public int IdAvance { get; set; }
        public int Valor { get; set; }
        public string Tipo { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public bool Automatica { get; set; }
        public Nullable<bool> OPTracker { get; set; }
        public string DescProcesoAut { get; set; }
        public Nullable<bool> Ganada { get; set; }
    }
}
