//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calif_Posibles_Resp
    {
        public int IdCalificacion { get; set; }
        public int Id_Pregunta { get; set; }
        public int Num_Respuesta { get; set; }
        public string Respuesta { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
