//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calif_Preguntas
    {
        public int IdCalificacion { get; set; }
        public int Id_Pregunta { get; set; }
        public int Num_Pregunta { get; set; }
        public string Pregunta { get; set; }
        public Nullable<int> Id_Atributo { get; set; }
        public bool CompetenciaActivoPreg { get; set; }
        public bool Activo { get; set; }
    }
}
