//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalifxOp
    {
        public int CveOport { get; set; }
        public string Folio_Op { get; set; }
        public int IdCalificacion { get; set; }
        public System.DateTime Fecha_Calif { get; set; }
        public int Id_TipoCalif { get; set; }
        public string Tipo_Calif { get; set; }
        public Nullable<int> Num_Tipo { get; set; }
        public string Nombre_Comp { get; set; }
        public int Id_Pregunta { get; set; }
        public Nullable<int> Num_Pregunta { get; set; }
        public string Pregunta { get; set; }
        public Nullable<int> Id_Atributo { get; set; }
        public Nullable<int> Num_Atributo { get; set; }
        public string Atributo { get; set; }
        public Nullable<double> ValorAtributo { get; set; }
        public Nullable<int> Num_Respuesta { get; set; }
        public string Respuesta { get; set; }
        public Nullable<double> ValorRespuesta { get; set; }
        public Nullable<double> ValorTotalCalif { get; set; }
        public string RegistradoPor { get; set; }
    }
}
