//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calif_Tipo_V1
    {
        public int Id_TipoCalif { get; set; }
        public string Tipo_Calif { get; set; }
        public Nullable<int> Num_Tipo { get; set; }
        public string Desc_Tipo { get; set; }
        public Nullable<bool> Estatus_Captura { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
