//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes_Potenciales
    {
        public decimal idProspecto { get; set; }
        public string Zona_Prospecto { get; set; }
        public string Num_Prospecto { get; set; }
        public string Razon_Social { get; set; }
        public string Num_Corp { get; set; }
        public string Corporativo { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string CP { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string RFC { get; set; }
        public string Habilitado { get; set; }
        public string pagina_web { get; set; }
        public string agrupador_1 { get; set; }
        public string agrupador_2 { get; set; }
        public string agrupador_3 { get; set; }
        public string agrupador_4 { get; set; }
        public Nullable<bool> mkt_resp { get; set; }
        public Nullable<int> nuevo_reg { get; set; }
        public Nullable<System.DateTime> fechaalta_reg { get; set; }
        public string usualta_reg { get; set; }
        public Nullable<System.DateTime> fechaact_reg { get; set; }
        public string usuact_reg { get; set; }
        public string Notas { get; set; }
        public string Usu_Carga { get; set; }
        public Nullable<int> Tipo_Carga { get; set; }
        public Nullable<int> StatusAut_Mkt { get; set; }
        public string Rechazo_Mkt { get; set; }
        public string UsuAsig_Mkt { get; set; }
        public Nullable<int> ClienteTra_Mkt { get; set; }
        public string UsuAsigno { get; set; }
        public Nullable<System.DateTime> FechaAsigno { get; set; }
    }
}
