//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compettmp
    {
        public string sesionid { get; set; }
        public string competencia { get; set; }
        public string Fortalezas { get; set; }
        public string Debilidades { get; set; }
        public string Proy_cuenta { get; set; }
        public Nullable<System.DateTime> antihuedad { get; set; }
    }
}
