//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactosOutlookTrash
    {
        public int CveContacto { get; set; }
        public string nombre_completo { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string apellidos { get; set; }
        public string CveCliente { get; set; }
        public string compania { get; set; }
        public string companiaTracker { get; set; }
        public string NombreCompaniaTracker { get; set; }
        public string puesto { get; set; }
        public string departamento { get; set; }
        public string GiroComercial { get; set; }
        public string cia_telefono { get; set; }
        public string cia_fax { get; set; }
        public string Titulo { get; set; }
        public string Asistente { get; set; }
        public string TelAsistente { get; set; }
        public string tel_casa { get; set; }
        public string tel_movil { get; set; }
        public string email { get; set; }
        public string email_2 { get; set; }
        public string email_3 { get; set; }
        public string webpage { get; set; }
        public string pager { get; set; }
        public string casa_direccion { get; set; }
        public string casa_colonia { get; set; }
        public string casa_cp { get; set; }
        public string casa_ciudad { get; set; }
        public string casa_pais { get; set; }
        public string casa_estado { get; set; }
        public string alias { get; set; }
        public string cia_direccion { get; set; }
        public string cia_colonia { get; set; }
        public string cia_ciudad { get; set; }
        public string cia_estado { get; set; }
        public string cia_cp { get; set; }
        public string cia_pais { get; set; }
        public string usuario { get; set; }
        public string CveUsuario { get; set; }
        public Nullable<bool> llamar { get; set; }
        public string Notas { get; set; }
        public Nullable<System.DateTime> fecha_Actualizacion { get; set; }
        public Nullable<System.DateTime> fecha_cumple { get; set; }
        public Nullable<int> idCliente_mkt { get; set; }
    }
}
