//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public string CveCliente { get; set; }
        public string Nombre_cli { get; set; }
        public string NomContacto { get; set; }
        public string Puesto { get; set; }
        public string Departamento { get; set; }
        public string GiroComercial { get; set; }
        public string Titulo { get; set; }
        public string Asistente { get; set; }
        public string TelAsistente { get; set; }
        public string TelTrabajo { get; set; }
        public string FaxTrabajo { get; set; }
        public string TelCasa { get; set; }
        public string TelPortatil { get; set; }
        public string email_1 { get; set; }
        public string email_2 { get; set; }
        public string email_3 { get; set; }
        public Nullable<int> tipodireccion { get; set; }
        public string CalleyNo { get; set; }
        public string Colonia { get; set; }
        public string CodPostal { get; set; }
        public Nullable<int> CveCiudad { get; set; }
        public Nullable<int> CveEstado { get; set; }
        public string Pais { get; set; }
        public string llamar { get; set; }
        public string usuario { get; set; }
        public int CveCont { get; set; }
        public string WebSite { get; set; }
        public string Notas { get; set; }
    }
}
