//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricaxOp
    {
        public int CveOportunidad { get; set; }
        public int CveFabrica { get; set; }
        public string DescProy { get; set; }
        public string RespFab { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> MargenFab { get; set; }
        public string CatMargenfab { get; set; }
        public string OtraFab { get; set; }
        public string CveConsultor { get; set; }
        public string Consultor { get; set; }
        public string LoginConsultor { get; set; }
        public Nullable<int> IdFabricante { get; set; }
        public string OtroFabricante { get; set; }
        public Nullable<int> PorcParticipacion { get; set; }
        public Nullable<bool> LNPrincipal { get; set; }
        public string Cve_Clasificador { get; set; }
    }
}
