//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabricas
    {
        public int CveFabrica { get; set; }
        public string DescFabrica { get; set; }
        public string E_ger { get; set; }
        public string Responsable { get; set; }
        public string ClaveDln { get; set; }
        public Nullable<short> Estatus { get; set; }
        public Nullable<double> Montoring { get; set; }
        public Nullable<int> area_pmtracker { get; set; }
        public Nullable<int> habilitada { get; set; }
        public Nullable<bool> precierre { get; set; }
        public Nullable<int> Habilita_Email_Grupo { get; set; }
        public string Email_grupo { get; set; }
        public Nullable<int> Habilita_Total_Horas { get; set; }
        public Nullable<bool> Requiere_Auto_Ingenieria { get; set; }
    }
}
