//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricaTmp
    {
        public string Sesionid { get; set; }
        public int CveFabrica { get; set; }
        public string OtraFab { get; set; }
        public string Comentarios { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Margen { get; set; }
        public string MargenCat { get; set; }
        public string Responsable { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string Consultor { get; set; }
        public string LoginConsultor { get; set; }
        public Nullable<int> IdFabricante { get; set; }
        public string OtroFabricante { get; set; }
        public Nullable<int> PorcParticipacion { get; set; }
        public Nullable<bool> LNPrincipal { get; set; }
        public string Modulo { get; set; }
        public string Cve_Clasificador { get; set; }
    }
}
