//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabricantes
    {
        public int IdFabricante { get; set; }
        public string NomFabricante { get; set; }
        public bool OtroFabricante { get; set; }
        public string UsuRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public bool Activo { get; set; }
    }
}
