//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filtros_Usuarios
    {
        public int IdFiltro { get; set; }
        public int TipoFiltro { get; set; }
        public string Login { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string FechaModificacion { get; set; }
    }
}
