//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistReaperturaOp
    {
        public string Folio_Op { get; set; }
        public string Login_Reapertura { get; set; }
        public System.DateTime Fecha_Reapertura { get; set; }
        public string Comentario { get; set; }
    }
}
