//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP_ScoreBoard_Historia
    {
        public string Login { get; set; }
        public System.DateTime Fecha_Inicial { get; set; }
        public System.DateTime Fecha_Final { get; set; }
        public int NumOP { get; set; }
        public int NumOP_Migradas { get; set; }
        public double Porc_Migradas { get; set; }
        public int NumOP_Vencidas { get; set; }
        public double Porc_Vencidas { get; set; }
        public int NumOP_Propuesta { get; set; }
        public double Porc_Propuesta { get; set; }
        public int Num_Visitas { get; set; }
    }
}
