//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oportunidad
    {
        public int CveOport { get; set; }
        public Nullable<int> clave_proyecto { get; set; }
        public string folio_proyecto { get; set; }
        public string DescOp { get; set; }
        public string Cliente { get; set; }
        public string NombCli { get; set; }
        public string ZonaCli { get; set; }
        public string Resp_m { get; set; }
        public string Detecto { get; set; }
        public string Probabilidad { get; set; }
        public Nullable<int> ContactoR { get; set; }
        public string TomaDesi { get; set; }
        public Nullable<System.DateTime> FAltaOp { get; set; }
        public Nullable<System.DateTime> FEstDesi { get; set; }
        public Nullable<int> Fuente { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> Etapa { get; set; }
        public Nullable<System.DateTime> FechaAct { get; set; }
        public string ActPor { get; set; }
        public string ComFabrica { get; set; }
        public string ComComercial { get; set; }
        public string ComMarketing { get; set; }
        public string ComCierre { get; set; }
        public Nullable<decimal> MontoOp { get; set; }
        public Nullable<decimal> MargenB { get; set; }
        public Nullable<int> Moneda { get; set; }
        public string Competencias { get; set; }
        public string ComAdic { get; set; }
        public string Cerrada { get; set; }
        public string Autorizada { get; set; }
        public string AutPor { get; set; }
        public Nullable<System.DateTime> FAuto { get; set; }
        public string CatMargen { get; set; }
        public string ComRechazo { get; set; }
        public string Otro { get; set; }
        public string ContaResp { get; set; }
        public string RespTecnico { get; set; }
        public string Folio_Op { get; set; }
        public string ReferOp { get; set; }
        public string ConsTecnico { get; set; }
        public Nullable<decimal> MontoFinal { get; set; }
        public Nullable<decimal> MargenFinal { get; set; }
        public string CompetenciaFinal { get; set; }
        public Nullable<System.DateTime> fi_facturacion { get; set; }
        public Nullable<int> idCliente_mkt { get; set; }
        public Nullable<int> UltimaActividad { get; set; }
        public Nullable<System.DateTime> UltimaFechaAct { get; set; }
        public string UltimoRespAct { get; set; }
        public Nullable<System.DateTime> UltimaFechaCompAct { get; set; }
        public string UltimoUsuRegAct { get; set; }
        public Nullable<double> Calificacion { get; set; }
        public Nullable<int> Avance { get; set; }
        public Nullable<double> CalificacionCompeten { get; set; }
        public string ColorAvanceSemanal { get; set; }
        public Nullable<System.DateTime> FechaActualAvance { get; set; }
        public string UsuActualAvance { get; set; }
        public Nullable<System.DateTime> Fecha_Activacion { get; set; }
        public string Usuario_Activacion { get; set; }
        public Nullable<System.DateTime> Fecha_MovActiv { get; set; }
        public Nullable<bool> precierre { get; set; }
        public Nullable<System.DateTime> fecha_precierre { get; set; }
        public string usu_precierre { get; set; }
        public string comentprecierre { get; set; }
        public Nullable<System.DateTime> FechaCompromisoCierre { get; set; }
        public string AutorizaIng { get; set; }
        public string AutorizadoxIng { get; set; }
        public Nullable<System.DateTime> FechaAutIng { get; set; }
        public string ComAutorizaIng { get; set; }
        public string ComCierreSinAut { get; set; }
        public Nullable<int> id_ContaResp { get; set; }
        public Nullable<int> id_TomaDesi { get; set; }
        public Nullable<int> Id_CNSC_TiposFuentes { get; set; }
        public Nullable<System.DateTime> FechaCierreIng { get; set; }
        public string LoginCierreIng { get; set; }
        public Nullable<int> bit_VentaCruzada { get; set; }
        public Nullable<int> Id_CNSC_ProgramaVentas { get; set; }
        public string FolioFabricante { get; set; }
    }
}
