//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OPTrackerEntities : DbContext
    {
        public OPTrackerEntities()
            : base("name=OPTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aplicaciones> Aplicaciones { get; set; }
        public virtual DbSet<AplicacionesPermiso> AplicacionesPermiso { get; set; }
        public virtual DbSet<Calif_Atributos> Calif_Atributos { get; set; }
        public virtual DbSet<Calif_Atributos_V1> Calif_Atributos_V1 { get; set; }
        public virtual DbSet<Calif_Posibles_Resp> Calif_Posibles_Resp { get; set; }
        public virtual DbSet<Calif_Posibles_Resp_V1> Calif_Posibles_Resp_V1 { get; set; }
        public virtual DbSet<Calif_Preguntas> Calif_Preguntas { get; set; }
        public virtual DbSet<Calif_Preguntas_V1> Calif_Preguntas_V1 { get; set; }
        public virtual DbSet<CalifxOp> CalifxOp { get; set; }
        public virtual DbSet<ContactosOutlook> ContactosOutlook { get; set; }
        public virtual DbSet<ContactosOutlookV1> ContactosOutlookV1 { get; set; }
        public virtual DbSet<ContactosPROOutlook> ContactosPROOutlook { get; set; }
        public virtual DbSet<Fabricas> Fabricas { get; set; }
        public virtual DbSet<HistOPComprometidas> HistOPComprometidas { get; set; }
        public virtual DbSet<NivelesdeUsuario> NivelesdeUsuario { get; set; }
        public virtual DbSet<Oportunidad> Oportunidad { get; set; }
        public virtual DbSet<TblAreas> TblAreas { get; set; }
        public virtual DbSet<tblCorporativos> tblCorporativos { get; set; }
        public virtual DbSet<tblDocsMarketing> tblDocsMarketing { get; set; }
        public virtual DbSet<TblEstatusCliente> TblEstatusCliente { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Accesos> Accesos { get; set; }
        public virtual DbSet<Actividades> Actividades { get; set; }
        public virtual DbSet<ActivxClie> ActivxClie { get; set; }
        public virtual DbSet<ActivxClieEliminadas> ActivxClieEliminadas { get; set; }
        public virtual DbSet<ActivxOp> ActivxOp { get; set; }
        public virtual DbSet<activxop2> activxop2 { get; set; }
        public virtual DbSet<ActivxOpEliminadas> ActivxOpEliminadas { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Avances> Avances { get; set; }
        public virtual DbSet<Avances_Color> Avances_Color { get; set; }
        public virtual DbSet<Calif_Tipo> Calif_Tipo { get; set; }
        public virtual DbSet<Calif_Tipo_V1> Calif_Tipo_V1 { get; set; }
        public virtual DbSet<CalifTmp> CalifTmp { get; set; }
        public virtual DbSet<Clientes_MKT> Clientes_MKT { get; set; }
        public virtual DbSet<Clientes_MKT_Trash> Clientes_MKT_Trash { get; set; }
        public virtual DbSet<Clientes_Potenciales> Clientes_Potenciales { get; set; }
        public virtual DbSet<Competencia> Competencia { get; set; }
        public virtual DbSet<Compettmp> Compettmp { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<Contactos_Tipos> Contactos_Tipos { get; set; }
        public virtual DbSet<ContactosOutlookTrash> ContactosOutlookTrash { get; set; }
        public virtual DbSet<Fabricantes> Fabricantes { get; set; }
        public virtual DbSet<FabricaTmp> FabricaTmp { get; set; }
        public virtual DbSet<FabricaxOp> FabricaxOp { get; set; }
        public virtual DbSet<Filtros_Campos> Filtros_Campos { get; set; }
        public virtual DbSet<Filtros_Consultas> Filtros_Consultas { get; set; }
        public virtual DbSet<Filtros_ConsultasBKP> Filtros_ConsultasBKP { get; set; }
        public virtual DbSet<Filtros_Nivel> Filtros_Nivel { get; set; }
        public virtual DbSet<Filtros_Operadores> Filtros_Operadores { get; set; }
        public virtual DbSet<Filtros_Tipos> Filtros_Tipos { get; set; }
        public virtual DbSet<Filtros_Usuarios> Filtros_Usuarios { get; set; }
        public virtual DbSet<Fuentes> Fuentes { get; set; }
        public virtual DbSet<HistReaperturaOp> HistReaperturaOp { get; set; }
        public virtual DbSet<OP_ScoreBoard_Historia> OP_ScoreBoard_Historia { get; set; }
        public virtual DbSet<sugerencias> sugerencias { get; set; }
        public virtual DbSet<tb_TiposUsuario_Aplicaciones> tb_TiposUsuario_Aplicaciones { get; set; }
        public virtual DbSet<tbl_Archivos> tbl_Archivos { get; set; }
        public virtual DbSet<tbl_CatValoracion> tbl_CatValoracion { get; set; }
        public virtual DbSet<tbl_Compromisos> tbl_Compromisos { get; set; }
        public virtual DbSet<tbl_Compromisos_tmp> tbl_Compromisos_tmp { get; set; }
        public virtual DbSet<tbl_CompromisosDependentes> tbl_CompromisosDependentes { get; set; }
        public virtual DbSet<tbl_Configuraciones> tbl_Configuraciones { get; set; }
        public virtual DbSet<tbl_Cotizacion> tbl_Cotizacion { get; set; }
        public virtual DbSet<tbl_DetalleFuentes> tbl_DetalleFuentes { get; set; }
        public virtual DbSet<tbl_HorarioLaboral> tbl_HorarioLaboral { get; set; }
        public virtual DbSet<tbl_OportModMargenBruto> tbl_OportModMargenBruto { get; set; }
        public virtual DbSet<tbl_ProgramaVentas> tbl_ProgramaVentas { get; set; }
        public virtual DbSet<tbl_TipoCotizacion> tbl_TipoCotizacion { get; set; }
        public virtual DbSet<tbl_TipoMoneda> tbl_TipoMoneda { get; set; }
        public virtual DbSet<tbl_TituloGrafica> tbl_TituloGrafica { get; set; }
        public virtual DbSet<tbl_VentaCruzada> tbl_VentaCruzada { get; set; }
        public virtual DbSet<tblAccesosCarga> tblAccesosCarga { get; set; }
        public virtual DbSet<tblActividades> tblActividades { get; set; }
        public virtual DbSet<tblBitacora> tblBitacora { get; set; }
        public virtual DbSet<TblClasifLn> TblClasifLn { get; set; }
        public virtual DbSet<TblCuotas> TblCuotas { get; set; }
        public virtual DbSet<tblDocumentos> tblDocumentos { get; set; }
        public virtual DbSet<TblFuenteCliente> TblFuenteCliente { get; set; }
        public virtual DbSet<tblParametros> tblParametros { get; set; }
        public virtual DbSet<TblPublicaciones> TblPublicaciones { get; set; }
        public virtual DbSet<TblRespClasifLn> TblRespClasifLn { get; set; }
        public virtual DbSet<TblRespLN> TblRespLN { get; set; }
        public virtual DbSet<tblStatusComp> tblStatusComp { get; set; }
        public virtual DbSet<tblTipoActividades> tblTipoActividades { get; set; }
        public virtual DbSet<tblTipoActividadPreventa> tblTipoActividadPreventa { get; set; }
        public virtual DbSet<tblTipoDoc> tblTipoDoc { get; set; }
        public virtual DbSet<tbltitulos> tbltitulos { get; set; }
        public virtual DbSet<TblVisitasClientes> TblVisitasClientes { get; set; }
        public virtual DbSet<TblVisitasClientesbkp> TblVisitasClientesbkp { get; set; }
        public virtual DbSet<TblVisitasClientesTrash> TblVisitasClientesTrash { get; set; }
        public virtual DbSet<tbStatusCarga> tbStatusCarga { get; set; }
        public virtual DbSet<tmpFolioOp> tmpFolioOp { get; set; }
        public virtual DbSet<UsuariosporAreas> UsuariosporAreas { get; set; }
    }
}
