//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Configuraciones
    {
        public int Id_CNSC_Config { get; set; }
        public Nullable<int> CveFabrica { get; set; }
        public string EmailAltaComp { get; set; }
        public string SelectRepComp { get; set; }
        public Nullable<bool> BitActivo { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string UsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public string UsuarioMod { get; set; }
        public Nullable<int> IdCompromiso { get; set; }
        public Nullable<byte> PorcentajeMargen { get; set; }
        public string UsuarioNotifi { get; set; }
        public string ComentsConfi { get; set; }
    }
}
