//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OportModMargenBruto
    {
        public int Id_CNSC_OportMod { get; set; }
        public Nullable<int> cveOport { get; set; }
        public string usuRegAct { get; set; }
        public Nullable<decimal> PorcHorasNew { get; set; }
        public Nullable<bool> BitActivo { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string UsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public string UsuarioMod { get; set; }
    }
}
