//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DetalleFuentes
    {
        public int Id_CNSC_TiposFuentes { get; set; }
        public Nullable<int> CveFuente { get; set; }
        public string DescCorta_Evento { get; set; }
        public string Lugar_Evento { get; set; }
        public Nullable<System.DateTime> Fecha_Evento { get; set; }
        public string DescLarga_Evento { get; set; }
        public Nullable<bool> BitActivo { get; set; }
        public string UsuarioReg { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string UsuarioMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<bool> BitCombo { get; set; }
    }
}
