//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HorarioLaboral
    {
        public int Id_CNSC_HorarioLab { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> HorarioIni { get; set; }
        public Nullable<System.DateTime> HorarioFin { get; set; }
        public Nullable<int> TotalMin { get; set; }
        public Nullable<bool> BitActivo { get; set; }
        public string UsuReg { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string UsuMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    }
}
