//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccesosCarga
    {
        public int idAcceso { get; set; }
        public string Login { get; set; }
        public Nullable<System.DateTime> FechaAcceso { get; set; }
        public string UsuarioAcceso { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
