//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblClasifLn
    {
        public string Cve_Clasificador { get; set; }
        public string Desc_Clasificador { get; set; }
        public int Nivel_Clasificador { get; set; }
        public bool Estatus_Clasificador { get; set; }
        public int CveFabrica { get; set; }
    }
}
