//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocsMarketing
    {
        public int idDocumento { get; set; }
        public string idCliente { get; set; }
        public string CveUsuario { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> Fecha_alta { get; set; }
    }
}
