//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEstatusCliente
    {
        public int IdEstatusCliente { get; set; }
        public string EstatusCliente { get; set; }
        public int NumEstatus { get; set; }
        public bool Default { get; set; }
        public int SigEstatus { get; set; }
        public int DuracionDiasEstatus { get; set; }
    }
}
