//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParametros
    {
        public int DiasCierreAut { get; set; }
        public int Aviso1CierreAut { get; set; }
        public int Aviso2CierreAut { get; set; }
        public int Aviso3CierreAut { get; set; }
        public string EmailAvisoSupervisor { get; set; }
        public int DiasReaperturaOport { get; set; }
        public Nullable<int> Etapapropuesta { get; set; }
        public int DiasCompromisoOp { get; set; }
        public Nullable<int> DiasActPreventa { get; set; }
    }
}
