//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPublicaciones
    {
        public int NumPublicacion { get; set; }
        public Nullable<int> TipoPub { get; set; }
        public string DescPublicacion { get; set; }
        public string RespAsignado { get; set; }
        public Nullable<System.DateTime> FechaIniPub { get; set; }
        public Nullable<System.DateTime> FechaFinPub { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string RegistradoPor { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public Nullable<System.DateTime> FechaUltActualiza { get; set; }
        public string ActualizadoPor { get; set; }
    }
}
