//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRespLN
    {
        public int idCliente { get; set; }
        public Nullable<int> CveFabrica { get; set; }
        public string idUsuario { get; set; }
        public string Nombre_usuario { get; set; }
        public Nullable<System.DateTime> FecAsignado { get; set; }
        public string idAsignadoPor { get; set; }
        public string Nombre_AsignadoPor { get; set; }
        public Nullable<System.DateTime> FecUltimaActual { get; set; }
        public string idUsuUltimaActual { get; set; }
        public string Nombre_UltimaActual { get; set; }
    }
}
