//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTipoActividadPreventa
    {
        public int TipoActividad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Corto { get; set; }
        public string FolioDefault { get; set; }
    }
}
