//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVisitasClientes
    {
        public int CveVisita { get; set; }
        public string CveUsuario { get; set; }
        public Nullable<int> CveContacto { get; set; }
        public string Objetivo_visita { get; set; }
        public Nullable<bool> cumplio_objetivo { get; set; }
        public string compromisos { get; set; }
        public Nullable<bool> cliente_nuevo { get; set; }
        public Nullable<System.DateTime> fecha_visita { get; set; }
        public Nullable<System.DateTime> fecha_Actualizacion { get; set; }
        public Nullable<int> idCliente_mkt { get; set; }
        public Nullable<int> CveOport { get; set; }
        public string Folio_Op { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> tipoact { get; set; }
    }
}
