//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpFolioOp
    {
        public int CveOport { get; set; }
        public Nullable<System.DateTime> FechaAct { get; set; }
        public string ActPor { get; set; }
        public string Folio_Op { get; set; }
        public Nullable<System.DateTime> FechaActualAvance { get; set; }
        public string UsuActualAvance { get; set; }
    }
}
