//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.OPTRACKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string CveUsuario { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string Gerencia { get; set; }
        public Nullable<int> Fabrica { get; set; }
        public Nullable<int> Area { get; set; }
        public string email { get; set; }
        public Nullable<int> Depart { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> ActMkt { get; set; }
        public Nullable<int> idUsuPMTracker { get; set; }
        public Nullable<int> DiasPromFactur { get; set; }
        public Nullable<bool> GeneraProyecto { get; set; }
        public Nullable<bool> AutorizaPrecierre { get; set; }
        public Nullable<bool> ReportNotifi { get; set; }
        public Nullable<bool> BitModKPIprev { get; set; }
        public Nullable<bool> BitModKPIimp { get; set; }
        public Nullable<bool> BitModKPIsop { get; set; }
        public Nullable<bool> BitModKPIproy { get; set; }
    }
}
