//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes_PM
    {
        public int clave_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public string CveCliente_ERP { get; set; }
        public Nullable<decimal> idClienteTracker { get; set; }
    }
}
