//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes_SaiLine
    {
        public string ciudad { get; set; }
        public string estado { get; set; }
        public Nullable<double> tpo_atencion { get; set; }
        public string tpo_solucion { get; set; }
        public string cp { get; set; }
        public string fax { get; set; }
        public string telefono { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string clave { get; set; }
        public string num_factura { get; set; }
        public Nullable<System.DateTime> fecha_factura { get; set; }
        public string ubicacion { get; set; }
        public Nullable<int> prioridad_tel { get; set; }
        public string password_sn { get; set; }
        public string ejecutivo { get; set; }
        public Nullable<double> credito { get; set; }
        public Nullable<int> margen { get; set; }
        public string nombre_corto { get; set; }
        public string clave_contrato { get; set; }
        public string raz_soc { get; set; }
        public string rfc { get; set; }
        public Nullable<int> corporativo { get; set; }
        public string change_uid { get; set; }
        public Nullable<System.DateTime> change_dt { get; set; }
        public string sync_uid { get; set; }
        public Nullable<System.DateTime> sync_dt { get; set; }
        public Nullable<int> encuesta { get; set; }
        public Nullable<bool> Datos_Telmex { get; set; }
    }
}
