//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobranza_tblLogError
    {
        public decimal LogId { get; set; }
        public string Accion { get; set; }
        public string Mensaje { get; set; }
        public string Source { get; set; }
        public string StackTrace { get; set; }
    }
}
