//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobranza_tblRechazos
    {
        public decimal RechazoId { get; set; }
        public Nullable<decimal> CobranzaId { get; set; }
        public string DocumentoNo { get; set; }
        public Nullable<int> Cve_Empresa { get; set; }
        public Nullable<int> EstatusRechazoId { get; set; }
        public Nullable<int> MotivoRechazoId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificado { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<int> EstatusEnviarId { get; set; }
        public string NombreEnvio { get; set; }
        public string EmailEnvio { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<int> SubMotivoRechazoId { get; set; }
    
        public virtual Cobranza_tblAreas Cobranza_tblAreas { get; set; }
        public virtual Cobranza_tblCobranzas Cobranza_tblCobranzas { get; set; }
        public virtual Cobranza_tblEstatusEnviar Cobranza_tblEstatusEnviar { get; set; }
        public virtual Cobranza_tblEstatusRechazos Cobranza_tblEstatusRechazos { get; set; }
        public virtual Cobranza_tblMotivosRechazos Cobranza_tblMotivosRechazos { get; set; }
        public virtual Cobranza_tblSubMotivosRechazos Cobranza_tblSubMotivosRechazos { get; set; }
    }
}
