//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobranza_tblClientes
    {
        public decimal ClienteId { get; set; }
        public string NoCliente { get; set; }
        public string Nombre { get; set; }
        public string NoCorporativo { get; set; }
        public string Corporativo { get; set; }
        public string PaginaWeb { get; set; }
        public string UsuarioMicro { get; set; }
        public string PasswordMicro { get; set; }
        public string UsuarioMigesa { get; set; }
        public string PasswordMigesa { get; set; }
        public string UsuarioCapta { get; set; }
        public string PasswordCapta { get; set; }
        public string UsuarioConnext { get; set; }
        public string PasswordConnext { get; set; }
        public string EmailEnvio { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> FechaModificado { get; set; }
        public string ModificadoPor { get; set; }
    }
}
