//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobranza_tblCobranzas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cobranza_tblCobranzas()
        {
            this.Cobranza_tblAprobaciones = new HashSet<Cobranza_tblAprobaciones>();
            this.Cobranza_tblRechazos = new HashSet<Cobranza_tblRechazos>();
            this.Cobranza_tblSeguimientosAprobaciones = new HashSet<Cobranza_tblSeguimientosAprobaciones>();
            this.Cobranza_tblSeguimientosRechazos = new HashSet<Cobranza_tblSeguimientosRechazos>();
        }
    
        public decimal CobranzaId { get; set; }
        public string DocumentoNo { get; set; }
        public Nullable<int> Cve_Empresa { get; set; }
        public string RespCobranza { get; set; }
        public string Gerencia { get; set; }
        public string GestorDueño { get; set; }
        public string GestorActual { get; set; }
        public Nullable<int> EstatusInventarioId { get; set; }
        public string Comentarios { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificado { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<int> EstatusCobranza2Id { get; set; }
        public Nullable<System.DateTime> FechaEstatusCobranza2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobranza_tblAprobaciones> Cobranza_tblAprobaciones { get; set; }
        public virtual Tbl_Empresas Tbl_Empresas { get; set; }
        public virtual Cobranza_tblEstatusCobranzas2 Cobranza_tblEstatusCobranzas2 { get; set; }
        public virtual Cobranza_tblEstatusInventarios Cobranza_tblEstatusInventarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobranza_tblRechazos> Cobranza_tblRechazos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobranza_tblSeguimientosAprobaciones> Cobranza_tblSeguimientosAprobaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobranza_tblSeguimientosRechazos> Cobranza_tblSeguimientosRechazos { get; set; }
    }
}
