//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobranza_tblCobranzasPronosticosMensuales
    {
        public decimal CobranzaPronosticoMensualId { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Nombre_Empresa { get; set; }
        public string Numero_Cliente { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Referencia { get; set; }
        public string Pedido_Empresa { get; set; }
        public string Gestor_Actual { get; set; }
        public string Estatus_Cobranza_2_Anterior { get; set; }
        public string Estatus_Cobranza_2 { get; set; }
        public string Estatus_Inventario { get; set; }
        public string Estatus_Cobranza { get; set; }
        public string Sub_Estatus_Cobranza_1 { get; set; }
        public string Sub_Estatus_Cobranza_2 { get; set; }
        public string Fecha_Estimada_Cobro { get; set; }
        public string Año_Mes_Estimado_Cobro { get; set; }
        public string EstatusEnviar { get; set; }
        public string Motivo_No_Envio { get; set; }
        public string Fecha_Aprobación { get; set; }
        public string Nombre_Envio { get; set; }
        public string Email_Envio { get; set; }
        public string Comentarios_Aprobacion { get; set; }
        public string Fecha_Asignación { get; set; }
        public string Motivo_Rechazo { get; set; }
        public string Area_Asignacion { get; set; }
        public string Comentarios_Asignacion { get; set; }
        public string Vendedor { get; set; }
        public string Gerencia { get; set; }
        public string Pedido_de_Venta { get; set; }
        public string Cotizacion_Empresa { get; set; }
        public string Año_Mes_Exp_Fact { get; set; }
        public string Clasificacion_Fecha_Exp { get; set; }
        public string Fecha_Emision_Documento { get; set; }
        public string Vencimiento { get; set; }
        public Nullable<double> Importe_Inicial { get; set; }
        public Nullable<decimal> Importe_Pesos { get; set; }
        public Nullable<decimal> Importe_Dolares { get; set; }
        public Nullable<int> Dias_Vencidos { get; set; }
        public Nullable<decimal> Importe_Total_Pesos { get; set; }
        public Nullable<decimal> Miles_Pesos { get; set; }
        public string O_C__Cliente { get; set; }
        public string Folio_Fiscal { get; set; }
        public string CorporativoCliente { get; set; }
        public string Corporativo { get; set; }
        public string Cliente_Venta { get; set; }
        public string Cliente_Final { get; set; }
        public Nullable<double> TC_Documento { get; set; }
        public string Tipo_Pedido { get; set; }
        public string Area { get; set; }
        public string Resp_Area { get; set; }
        public string Unidad { get; set; }
        public string Resp_Unidad { get; set; }
        public string SubUnidad { get; set; }
        public string Resp_SubUnidad { get; set; }
        public string Resp_Gerencia { get; set; }
        public string Resp_Cobranza { get; set; }
        public string Zona_Cobranza { get; set; }
        public string Tipo_Facturacion { get; set; }
        public string Remision_Empresa { get; set; }
        public string FechaRemision { get; set; }
        public string Contacto { get; set; }
        public string Plaza_Vend { get; set; }
        public string CorporativoGrupos { get; set; }
        public string Nombre_Vendedor { get; set; }
        public string Nombre_Gestor { get; set; }
        public string Cód__Divisa { get; set; }
        public Nullable<int> Cve_Empresa { get; set; }
        public string Tipo_Documento { get; set; }
        public string Numero_Corporativo { get; set; }
        public string Gestor_Dueño { get; set; }
        public Nullable<double> TC_Dia { get; set; }
        public string IVACliente { get; set; }
        public string Tipo_Pedido_Desc { get; set; }
        public string No_Documento { get; set; }
        public string Cotizacion { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public string CreadoPor { get; set; }
    }
}
