//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobranza_tblUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cobranza_tblUsuarios()
        {
            this.Cobranza_tblEscalaciones = new HashSet<Cobranza_tblEscalaciones>();
            this.Cobranza_tblEscalaciones1 = new HashSet<Cobranza_tblEscalaciones>();
            this.Cobranza_tblEscalaciones2 = new HashSet<Cobranza_tblEscalaciones>();
        }
    
        public decimal UsuarioId { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> RolId { get; set; }
        public string NumEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Puesto { get; set; }
        public string Telefono { get; set; }
        public string Extension { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Gerencia { get; set; }
        public string Gestor { get; set; }
        public string Vendedor { get; set; }
        public string Comprador { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Cobranza_tblAreas Cobranza_tblAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobranza_tblEscalaciones> Cobranza_tblEscalaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobranza_tblEscalaciones> Cobranza_tblEscalaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobranza_tblEscalaciones> Cobranza_tblEscalaciones2 { get; set; }
        public virtual Cobranza_tblRoles Cobranza_tblRoles { get; set; }
    }
}
