//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobranza_tblSubEstatusCobranza2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cobranza_tblSubEstatusCobranza2()
        {
            this.Cobranza_tblSeguimientosAprobaciones = new HashSet<Cobranza_tblSeguimientosAprobaciones>();
        }
    
        public int SubEstatusCobranza2Id { get; set; }
        public Nullable<int> SubEstatusCobranza1Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cobranza_tblSeguimientosAprobaciones> Cobranza_tblSeguimientosAprobaciones { get; set; }
    }
}
