//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPED_Connext
    {
        public int CveEmpresa { get; set; }
        public string Empresa { get; set; }
        public string Documento { get; set; }
        public int Line_No_ { get; set; }
        public string Pay_to_Vendor_No_ { get; set; }
        public string Pay_to_Name { get; set; }
        public System.DateTime FechaCPED { get; set; }
        public string Currency_Code { get; set; }
        public Nullable<decimal> TC { get; set; }
        public string Purchaser_Code { get; set; }
        public string Producto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public decimal Direct_Unit_Cost { get; set; }
        public Nullable<decimal> CostoOriginal { get; set; }
        public Nullable<decimal> CostoAjustado { get; set; }
        public int Pedido { get; set; }
    }
}
