//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadosActiveDirectory
    {
        public Nullable<double> No_Empleado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Area_Administrativa { get; set; }
        public Nullable<double> Centro_de_Costos { get; set; }
        public string Apellidos_Buscar { get; set; }
        public string Apellidos_AD { get; set; }
        public bool Usuario_OK { get; set; }
        public string Usuario_Red { get; set; }
        public string Correo { get; set; }
        public bool Actualizar_Nav { get; set; }
    }
}
