//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Relative
    {
        public byte[] timestamp { get; set; }
        public string Employee_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Relative_Code { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Phone_No_ { get; set; }
        public string Relative_s_Employee_No_ { get; set; }
        public int Autorizado { get; set; }
    }
}
