//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePasoPrueba
    {
        public byte[] timestampP { get; set; }
        public string No_P { get; set; }
        public string First_NameP { get; set; }
        public string Middle_NameP { get; set; }
        public string Last_NameP { get; set; }
        public string InitialsP { get; set; }
        public string Job_TitleP { get; set; }
        public string Search_NameP { get; set; }
        public string AddressP { get; set; }
        public string Address_2P { get; set; }
        public string CityP { get; set; }
        public string Post_CodeP { get; set; }
        public string CountyP { get; set; }
        public string Phone_No_P { get; set; }
        public string Mobile_Phone_No_P { get; set; }
        public string E_MailP { get; set; }
        public string Alt__Address_CodeP { get; set; }
        public System.DateTime Alt__Address_Start_DateP { get; set; }
        public System.DateTime Alt__Address_End_DateP { get; set; }
        public byte[] PictureP { get; set; }
        public System.DateTime Birth_DateP { get; set; }
        public string Social_Security_No_P { get; set; }
        public string Union_CodeP { get; set; }
        public string Union_Membership_No_P { get; set; }
        public int SexP { get; set; }
        public string Country_Region_CodeP { get; set; }
        public string Manager_No_P { get; set; }
        public int Emplymt__Contract_CodeP { get; set; }
        public string Statistics_Group_CodeP { get; set; }
        public System.DateTime Employment_DateP { get; set; }
        public int StatusP { get; set; }
        public System.DateTime Inactive_DateP { get; set; }
        public string Cause_of_Inactivity_CodeP { get; set; }
        public System.DateTime Termination_DateP { get; set; }
        public string Grounds_for_Term__CodeP { get; set; }
        public string Global_Dimension_1_CodeP { get; set; }
        public string Global_Dimension_2_CodeP { get; set; }
        public string Resource_No_P { get; set; }
        public System.DateTime Last_Date_ModifiedP { get; set; }
        public string ExtensionP { get; set; }
        public string PagerP { get; set; }
        public string Fax_No_P { get; set; }
        public string Company_E_MailP { get; set; }
        public string TitleP { get; set; }
        public string Salespers__Purch__CodeP { get; set; }
        public string No__SeriesP { get; set; }
        public string RFCP { get; set; }
        public string Lugar_de_NacimientoP { get; set; }
        public string CURPP { get; set; }
        public System.DateTime Fecha_Ultimo_AumentoP { get; set; }
        public string CC_DireccionP { get; set; }
        public string ClienteP { get; set; }
        public string Nombre_ClienteP { get; set; }
        public string Resp_Area_GerenciaP { get; set; }
        public string PuestoP { get; set; }
        public string Resp_AreaP { get; set; }
        public string Usuario_RedP { get; set; }
        public int Resp_GerenciaP { get; set; }
        public string Centro_de_CostosP { get; set; }
        public string No_Celular_OficinaP { get; set; }
        public string PuestoIdP { get; set; }
        public System.DateTime FechaInicioContratoP { get; set; }
        public System.DateTime FechaFinContratoP { get; set; }
        public string FM3NumeroP { get; set; }
        public string OnSiteP { get; set; }
        public int MotivoBajaP { get; set; }
        public string ComBajaP { get; set; }
        public string ComInactividadP { get; set; }
        public string Banco1P { get; set; }
        public string Cuenta1P { get; set; }
        public string Clabe1P { get; set; }
        public string Banco2P { get; set; }
        public string Cuenta2P { get; set; }
        public string Clabe2P { get; set; }
        public decimal BMontoP { get; set; }
        public string NumJefeP { get; set; }
        public string Tipo_EmpleadoP { get; set; }
        public string Ubicacion_EmpleadoP { get; set; }
        public string Funcion_EmpleadoP { get; set; }
        public string AreaP { get; set; }
        public string Responsable_DirP { get; set; }
        public string Responsable_GerP { get; set; }
        public string Estado_CivilP { get; set; }
        public string Duración_ContratoP { get; set; }
        public string FM3P { get; set; }
        public string CompañiaTelP { get; set; }
        public string Plan_CelularP { get; set; }
        public string SubordinadosP { get; set; }
        public string BonoP { get; set; }
        public string ComisionesP { get; set; }
        public string BPeriodoP { get; set; }
        public string CPeriodoP { get; set; }
        public string BTipoP { get; set; }
        public string UsuarioModP { get; set; }
        public string AreaAdministrativaP { get; set; }
        public string UsuarioRegistroP { get; set; }
        public System.DateTime FechaRegistroP { get; set; }
        public string EmpresaP { get; set; }
        public string HijosP { get; set; }
        public System.DateTime Fecha_Alta_IMSSP { get; set; }
        public int AutorizadoP { get; set; }
        public string MotivoModificacionP { get; set; }
        public string TipoBajaP { get; set; }
        public int ActivoFijoP { get; set; }
    }
}
