//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esquema_EmpleadoPaso
    {
        public byte[] timestampP { get; set; }
        public string EmpleadoP { get; set; }
        public string EsquemaPagoP { get; set; }
        public int LineaP { get; set; }
        public string DescripcionP { get; set; }
        public System.DateTime Fecha_InicioP { get; set; }
        public System.DateTime Fecha_FinalP { get; set; }
        public byte UtilizandoseP { get; set; }
        public string ComentarioP { get; set; }
        public decimal MontoP { get; set; }
        public decimal Porcentaje_IncrementoP { get; set; }
        public string UsuarioModP { get; set; }
        public System.DateTime FechaRegistroP { get; set; }
        public string UsuarioRegistroP { get; set; }
        public System.DateTime FechaModP { get; set; }
        public byte CanceladoP { get; set; }
        public string ComentariosP { get; set; }
        public int AutorizadoP { get; set; }
    }
}
