//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filtros_Gestor
    {
        public string Gestor { get; set; }
        public string Facturacion { get; set; }
        public string Unidad { get; set; }
        public string Corporativo { get; set; }
        public string Zona { get; set; }
        public string Resp { get; set; }
    }
}
