//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_O2C_Sharepoint
    {
        public int Identificador { get; set; }
        public string Folio { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ClaveVendedor { get; set; }
        public string ClienteRS { get; set; }
        public string NombreProyecto { get; set; }
        public Nullable<decimal> TotalVenta { get; set; }
        public Nullable<decimal> TotalCosto { get; set; }
        public Nullable<decimal> PorcentajeMargen { get; set; }
        public string Comprador { get; set; }
        public string CompradorAux { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Aviso { get; set; }
        public string CreadaPor { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaEstatus { get; set; }
    }
}
