//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Misc__Article_Information
    {
        public byte[] timestamp { get; set; }
        public string Employee_No_ { get; set; }
        public string Misc__Article_Code { get; set; }
        public int Line_No_ { get; set; }
        public string Description { get; set; }
        public System.DateTime From_Date { get; set; }
        public System.DateTime To_Date { get; set; }
        public byte In_Use { get; set; }
        public string Serial_No_ { get; set; }
        public decimal Monto_Dias { get; set; }
        public string UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int Autorizado { get; set; }
    }
}
