//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NAVINFOEntities : DbContext
    {
        public NAVINFOEntities()
            : base("name=NAVINFOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<c_valor_ganado> c_valor_ganado { get; set; }
        public virtual DbSet<Cobranza_tblAños> Cobranza_tblAños { get; set; }
        public virtual DbSet<Cobranza_tblAprobaciones> Cobranza_tblAprobaciones { get; set; }
        public virtual DbSet<Cobranza_tblAreas> Cobranza_tblAreas { get; set; }
        public virtual DbSet<Cobranza_tblClientes> Cobranza_tblClientes { get; set; }
        public virtual DbSet<Cobranza_tblCobranzas> Cobranza_tblCobranzas { get; set; }
        public virtual DbSet<Cobranza_tblCobranzasMensuales> Cobranza_tblCobranzasMensuales { get; set; }
        public virtual DbSet<Cobranza_tblCobranzasPronosticosMensuales> Cobranza_tblCobranzasPronosticosMensuales { get; set; }
        public virtual DbSet<Cobranza_tblEscalaciones> Cobranza_tblEscalaciones { get; set; }
        public virtual DbSet<Cobranza_tblEstatusCobranzas> Cobranza_tblEstatusCobranzas { get; set; }
        public virtual DbSet<Cobranza_tblEstatusCobranzas2> Cobranza_tblEstatusCobranzas2 { get; set; }
        public virtual DbSet<Cobranza_tblEstatusEnviar> Cobranza_tblEstatusEnviar { get; set; }
        public virtual DbSet<Cobranza_tblEstatusInventarios> Cobranza_tblEstatusInventarios { get; set; }
        public virtual DbSet<Cobranza_tblEstatusNoEnvios> Cobranza_tblEstatusNoEnvios { get; set; }
        public virtual DbSet<Cobranza_tblEstatusRechazos> Cobranza_tblEstatusRechazos { get; set; }
        public virtual DbSet<Cobranza_tblLogError> Cobranza_tblLogError { get; set; }
        public virtual DbSet<Cobranza_tblMeses> Cobranza_tblMeses { get; set; }
        public virtual DbSet<Cobranza_tblMotivosRechazos> Cobranza_tblMotivosRechazos { get; set; }
        public virtual DbSet<Cobranza_tblRechazos> Cobranza_tblRechazos { get; set; }
        public virtual DbSet<Cobranza_tblRoles> Cobranza_tblRoles { get; set; }
        public virtual DbSet<Cobranza_tblSeguimientosAprobaciones> Cobranza_tblSeguimientosAprobaciones { get; set; }
        public virtual DbSet<Cobranza_tblSeguimientosRechazos> Cobranza_tblSeguimientosRechazos { get; set; }
        public virtual DbSet<Cobranza_tblSubEstatusCobranza1> Cobranza_tblSubEstatusCobranza1 { get; set; }
        public virtual DbSet<Cobranza_tblSubEstatusCobranza2> Cobranza_tblSubEstatusCobranza2 { get; set; }
        public virtual DbSet<Cobranza_tblSubMotivosRechazos> Cobranza_tblSubMotivosRechazos { get; set; }
        public virtual DbSet<Cobranza_tblTiposActividades> Cobranza_tblTiposActividades { get; set; }
        public virtual DbSet<Cobranza_tblUsuarios> Cobranza_tblUsuarios { get; set; }
        public virtual DbSet<dias_festivos> dias_festivos { get; set; }
        public virtual DbSet<dias_inhabiles> dias_inhabiles { get; set; }
        public virtual DbSet<Employee_Relative> Employee_Relative { get; set; }
        public virtual DbSet<EmployeePaso> EmployeePaso { get; set; }
        public virtual DbSet<Esquema_EmpleadoPaso> Esquema_EmpleadoPaso { get; set; }
        public virtual DbSet<Horas_Trabajo_Ingenieros> Horas_Trabajo_Ingenieros { get; set; }
        public virtual DbSet<Misc__Article_Information> Misc__Article_Information { get; set; }
        public virtual DbSet<MotivosBaja> MotivosBaja { get; set; }
        public virtual DbSet<P_Pendientes> P_Pendientes { get; set; }
        public virtual DbSet<Puestos_Ingenieros> Puestos_Ingenieros { get; set; }
        public virtual DbSet<Relative> Relative { get; set; }
        public virtual DbSet<tb_PrecioVentaNav> tb_PrecioVentaNav { get; set; }
        public virtual DbSet<tb_ProductosNav> tb_ProductosNav { get; set; }
        public virtual DbSet<tbl_Concepto_Gasto_Operativo> tbl_Concepto_Gasto_Operativo { get; set; }
        public virtual DbSet<Tbl_Empresas> Tbl_Empresas { get; set; }
        public virtual DbSet<tbl_EstatusCobranza> tbl_EstatusCobranza { get; set; }
        public virtual DbSet<tbl_EstatusRechazo> tbl_EstatusRechazo { get; set; }
        public virtual DbSet<tbl_Gerencias> tbl_Gerencias { get; set; }
        public virtual DbSet<tbl_Grupos_Centro_Costos> tbl_Grupos_Centro_Costos { get; set; }
        public virtual DbSet<C_Prueba_Sharepoint_2> C_Prueba_Sharepoint_2 { get; set; }
        public virtual DbSet<Agrupadores_Diana> Agrupadores_Diana { get; set; }
        public virtual DbSet<Agrupadores_Diana_Respaldo> Agrupadores_Diana_Respaldo { get; set; }
        public virtual DbSet<Clientes_OP> Clientes_OP { get; set; }
        public virtual DbSet<Clientes_PM> Clientes_PM { get; set; }
        public virtual DbSet<Clientes_SaiLine> Clientes_SaiLine { get; set; }
        public virtual DbSet<Cobranza_tblCobranzasMensuales_Demo> Cobranza_tblCobranzasMensuales_Demo { get; set; }
        public virtual DbSet<dias_vacaciones> dias_vacaciones { get; set; }
        public virtual DbSet<EmpleadosActiveDirectory> EmpleadosActiveDirectory { get; set; }
        public virtual DbSet<EmployeePasoPrueba> EmployeePasoPrueba { get; set; }
        public virtual DbSet<Filtros_Gestor> Filtros_Gestor { get; set; }
        public virtual DbSet<Info_O2C_Sharepoint> Info_O2C_Sharepoint { get; set; }
        public virtual DbSet<Info_O2C_Sharepoint_V1> Info_O2C_Sharepoint_V1 { get; set; }
        public virtual DbSet<No_Operativos> No_Operativos { get; set; }
        public virtual DbSet<Oportunidad> Oportunidad { get; set; }
        public virtual DbSet<ScanNSBuffer_Log> ScanNSBuffer_Log { get; set; }
        public virtual DbSet<SeguimientoObtener> SeguimientoObtener { get; set; }
        public virtual DbSet<Sueldos2> Sueldos2 { get; set; }
        public virtual DbSet<Tb_Cubo_PmTracker_Horas_Devengadas> Tb_Cubo_PmTracker_Horas_Devengadas { get; set; }
        public virtual DbSet<Tb_Cubo_PmTracker_Horas_Devengadas_2> Tb_Cubo_PmTracker_Horas_Devengadas_2 { get; set; }
        public virtual DbSet<tb_Currency> tb_Currency { get; set; }
        public virtual DbSet<tb_PrecioVenta> tb_PrecioVenta { get; set; }
        public virtual DbSet<Tbl_Estructura_Area> Tbl_Estructura_Area { get; set; }
        public virtual DbSet<Tbl_Estructura_CC> Tbl_Estructura_CC { get; set; }
        public virtual DbSet<Tbl_Estructura_CC_old> Tbl_Estructura_CC_old { get; set; }
        public virtual DbSet<Tbl_Estructura_Gerencia> Tbl_Estructura_Gerencia { get; set; }
        public virtual DbSet<Tbl_Estructura_Grupo> Tbl_Estructura_Grupo { get; set; }
        public virtual DbSet<Tbl_Estructura_SubUnidad> Tbl_Estructura_SubUnidad { get; set; }
        public virtual DbSet<Tbl_Estructura_Unidad> Tbl_Estructura_Unidad { get; set; }
        public virtual DbSet<tbl_Productos_20121210> tbl_Productos_20121210 { get; set; }
        public virtual DbSet<tbl_Productos_20121210_Prueba> tbl_Productos_20121210_Prueba { get; set; }
        public virtual DbSet<tblCostoIngeniero> tblCostoIngeniero { get; set; }
        public virtual DbSet<tblSueldos> tblSueldos { get; set; }
        public virtual DbSet<V_ExplotacionActividades_OP> V_ExplotacionActividades_OP { get; set; }
        public virtual DbSet<V_ExplotacionActividades_PM> V_ExplotacionActividades_PM { get; set; }
        public virtual DbSet<V_ExplotacionActividades_PM1> V_ExplotacionActividades_PM1 { get; set; }
        public virtual DbSet<V_ExplotacionActividades_SaiLine> V_ExplotacionActividades_SaiLine { get; set; }
        public virtual DbSet<CPED_Connext> CPED_Connext { get; set; }
    }
}
