//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Pendientes
    {
        public int Identificador { get; set; }
        public Nullable<int> CveEmpresa { get; set; }
        public string Pedido { get; set; }
        public string Cotizacion { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<System.DateTime> FechaCotizacion { get; set; }
        public string NoCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Gerencia { get; set; }
        public string CCosto { get; set; }
        public string Vendedor { get; set; }
        public string OCCliente { get; set; }
        public string OrdenCompra { get; set; }
        public string CodigoCompra { get; set; }
        public Nullable<int> Linea { get; set; }
        public string Producto { get; set; }
        public string Descripcion { get; set; }
        public string Almacen { get; set; }
        public string UnidadMedida { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> T_C_ { get; set; }
        public Nullable<decimal> Cto__Unit__USD { get; set; }
        public Nullable<decimal> Cto__Unit__MN { get; set; }
        public Nullable<decimal> PVenta_USD { get; set; }
        public Nullable<decimal> PVenta_MN { get; set; }
        public Nullable<decimal> Importe_USD { get; set; }
        public Nullable<decimal> Importe_MN { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Cant__Reservada { get; set; }
        public Nullable<decimal> Cant__Reserva_Almacen { get; set; }
        public Nullable<decimal> Cant__Enviada { get; set; }
        public Nullable<decimal> Cant__Pdte__Enviar { get; set; }
        public Nullable<decimal> Cant__Enviada_No_Facturada { get; set; }
        public Nullable<decimal> Cant__Facturada { get; set; }
        public string RespGerencia { get; set; }
        public string Area { get; set; }
        public string RespArea { get; set; }
        public string Unidad { get; set; }
        public string RespUnidad { get; set; }
        public string SubUnidad { get; set; }
        public string RespSubUnidad { get; set; }
    }
}
