//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puestos_Ingenieros
    {
        public int id_puesto { get; set; }
        public string UsResp { get; set; }
        public string Puesto1 { get; set; }
        public Nullable<System.DateTime> Fecha_Cambio_Puesto { get; set; }
        public string Puesto2 { get; set; }
    }
}
