//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoObtener
    {
        public string EstatusInventario { get; set; }
        public decimal SeguimientoId { get; set; }
        public Nullable<decimal> CobranzaId { get; set; }
        public string DocumentoNo { get; set; }
        public string MotivoAsignacion { get; set; }
        public Nullable<int> TipoActividadId { get; set; }
        public string TipoActividad { get; set; }
        public string Actividad { get; set; }
        public Nullable<bool> AgendarLlamada { get; set; }
        public Nullable<System.DateTime> FechaActividad { get; set; }
        public Nullable<System.DateTime> FechaLlamada { get; set; }
        public string CreadoPor { get; set; }
        public string NombreCreado { get; set; }
        public Nullable<System.DateTime> FechaCreado { get; set; }
        public Nullable<int> Dias_Sin_Actualizar { get; set; }
        public string AsignadoA { get; set; }
        public Nullable<System.DateTime> FechaAsignado { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaSolucion { get; set; }
        public string Gestor_Dueño { get; set; }
        public string Gestor_Actual { get; set; }
        public int Cve_Empresa { get; set; }
        public string Nombre_Empresa { get; set; }
        public string Numero_Cliente { get; set; }
        public string Nombre_Cliente { get; set; }
        public string No_Documento { get; set; }
        public string Tipo_Documento { get; set; }
        public string Vendedor { get; set; }
        public string Nombre_Vendedor { get; set; }
        public string Gerencia { get; set; }
        public string Fecha_Emision_Documento { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public string Cód__Divisa { get; set; }
        public Nullable<int> Dias_Vencidos { get; set; }
        public string Pedido_de_Venta { get; set; }
        public string Corporativo { get; set; }
        public string AñoMes { get; set; }
        public string O_C__Cliente { get; set; }
        public string Nombre_Proyecto { get; set; }
        public string Folio_Fiscal { get; set; }
        public string Cliente_Venta { get; set; }
        public string Cliente_Final { get; set; }
        public string CorporativoGrupos { get; set; }
        public Nullable<double> Importe_Inicial { get; set; }
        public Nullable<decimal> Importe_Pesos { get; set; }
        public Nullable<decimal> Importe_Dolares { get; set; }
        public Nullable<decimal> Importe_Total_Pesos { get; set; }
        public Nullable<double> TC_Documento { get; set; }
        public Nullable<decimal> Por_Vencer { get; set; }
        public Nullable<decimal> Monto_Real_por_Vencer { get; set; }
        public Nullable<decimal> C1_15_días { get; set; }
        public Nullable<decimal> Monto_Real_1_15_días { get; set; }
        public Nullable<decimal> C16_30_días { get; set; }
        public Nullable<decimal> Monto_Real_16_30_días { get; set; }
        public Nullable<decimal> C31_45_días { get; set; }
        public Nullable<decimal> Monto_Real_31_45_días { get; set; }
        public Nullable<decimal> mas_de_45_días { get; set; }
        public Nullable<decimal> Monto_Real_mas_de_45_días { get; set; }
        public string Tipo_Pedido { get; set; }
        public string Area { get; set; }
        public string Resp_Area { get; set; }
        public string Unidad { get; set; }
        public string Resp_Unidad { get; set; }
        public string SubUnidad { get; set; }
        public string Resp_SubUnidad { get; set; }
        public string Resp_Gerencia { get; set; }
        public string Gestor { get; set; }
        public string Nombre_Gestor { get; set; }
        public Nullable<double> TC_Dia { get; set; }
        public string Resp_Cobranza { get; set; }
        public string Zona_Cobranza { get; set; }
        public string Cotizacion { get; set; }
        public string Code { get; set; }
        public string Contacto { get; set; }
        public string IVACliente { get; set; }
        public string Tipo_Pedido_Desc { get; set; }
        public string Tipo_Facturacion { get; set; }
    }
}
