//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PrecioVentaNav
    {
        public int CvePrecioVentaNav { get; set; }
        public string Item_No_ { get; set; }
        public int Sales_Type { get; set; }
        public string Sales_Code { get; set; }
        public System.DateTime Starting_Date { get; set; }
        public string Currency_Code { get; set; }
        public string Variant_Code { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public decimal Minimum_Quantity { get; set; }
        public string Programa { get; set; }
        public int Nivel { get; set; }
        public decimal Unit_Price { get; set; }
        public byte Price_Includes_VAT { get; set; }
        public byte Allow_Invoice_Disc_ { get; set; }
        public string VAT_Bus__Posting_Gr___Price_ { get; set; }
        public System.DateTime Ending_Date { get; set; }
        public byte Allow_Line_Disc_ { get; set; }
        public string Oferta { get; set; }
        public string Unidad_de_Compra { get; set; }
        public int Unidades_a_cuenta { get; set; }
        public decimal Costo_de_referencia { get; set; }
        public System.DateTime Fecha_referencia { get; set; }
    }
}
