//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PrecioVenta
    {
        public int CvePrecioVenta { get; set; }
        public string Part_Number { get; set; }
        public string Item_Name { get; set; }
        public string Program { get; set; }
        public string Offering { get; set; }
        public string Level { get; set; }
        public string Purchase_Unit { get; set; }
        public string Purchase_Period { get; set; }
        public string License_Agreement_Type { get; set; }
        public string Pool { get; set; }
        public Nullable<int> Unit_Count { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Current_Net_Price { get; set; }
        public Nullable<decimal> Estimated_Retail_Price { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
    }
}
