//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Gerencias
    {
        public string GERENCIA_ID { get; set; }
        public string UNIDAD { get; set; }
        public string RESPONSABLE { get; set; }
        public string DIVISION { get; set; }
        public string SUB_DIVISION { get; set; }
        public string UNIDAD_NEGOCIO { get; set; }
    }
}
