//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSueldos
    {
        public string Area_RH { get; set; }
        public Nullable<int> Num__Empleado { get; set; }
        public string Nombre_s_ { get; set; }
        public string Apellidos { get; set; }
        public string Fecha_de_Ingreso { get; set; }
        public string Fecha_de_Nacimiento { get; set; }
        public string Lugar_de_Nacimiento { get; set; }
        public string Estado_Civil { get; set; }
        public string Subordinados { get; set; }
        public string RFC { get; set; }
        public string Num_Seguro_Social { get; set; }
        public string CURP { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public string CP { get; set; }
        public string Banco_1 { get; set; }
        public string Cuenta_1 { get; set; }
        public string Clabe_1 { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Sexo { get; set; }
        public string Antiguedad { get; set; }
        public string Cliente_OnSite { get; set; }
        public string Centro_de_Costos { get; set; }
        public string Descripcion_Centro_de_Costos { get; set; }
        public decimal Monto_Aguinaldo { get; set; }
        public decimal Prima_Vacacional { get; set; }
        public string Ubicacion { get; set; }
        public string Puesto { get; set; }
        public string Area_Organizacional { get; set; }
        public string Funcion { get; set; }
        public string Tipo_de_Empleado { get; set; }
        public string Responsable_Direccion { get; set; }
        public string Responsable_Gerencia { get; set; }
        public string Jefe_Directo { get; set; }
        public Nullable<decimal> Adecco { get; set; }
        public Nullable<decimal> Asociado { get; set; }
        public Nullable<decimal> F___A_Asimilables { get; set; }
        public Nullable<decimal> F___A_Nomina { get; set; }
        public Nullable<decimal> Honorario_SP { get; set; }
        public Nullable<decimal> Persona_Moral { get; set; }
        public Nullable<decimal> Nomina_Migesa { get; set; }
        public Nullable<decimal> Nomina_Sigla { get; set; }
        public Nullable<decimal> Practicante { get; set; }
        public Nullable<decimal> Pequeños_Contribuyentes { get; set; }
        public Nullable<decimal> Apoyo_Capacitacion { get; set; }
        public Nullable<decimal> Aguinaldo { get; set; }
        public Nullable<decimal> Apoyo_Renta { get; set; }
        public Nullable<decimal> Automovil { get; set; }
        public Nullable<decimal> Bono_Decembrino { get; set; }
        public Nullable<decimal> Celular { get; set; }
        public Nullable<decimal> Estacionamiento { get; set; }
        public Nullable<decimal> Gasolina_y_Estacionamiento { get; set; }
        public Nullable<decimal> Mes_13 { get; set; }
        public Nullable<decimal> Pension_Automovil { get; set; }
        public Nullable<decimal> Plan_Empleado { get; set; }
        public Nullable<decimal> Utilidades { get; set; }
        public Nullable<decimal> Vacaciones { get; set; }
        public Nullable<decimal> Seguro_Gastos_Medicos { get; set; }
        public Nullable<decimal> Seguro_de_Vida { get; set; }
        public Nullable<decimal> Desempeño { get; set; }
        public Nullable<decimal> Soporte { get; set; }
        public Nullable<decimal> Implementaciones { get; set; }
        public Nullable<decimal> Comisiones { get; set; }
        public string Periodicidad { get; set; }
    }
}
