//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ExplotacionActividades_PM1
    {
        public string CveAct_OPPM { get; set; }
        public string Folio_op { get; set; }
        public string DescOP { get; set; }
        public string Nomb_Cliente { get; set; }
        public string EstatusOP { get; set; }
        public int CveAct { get; set; }
        public string UsResp { get; set; }
        public string respact { get; set; }
        public string Nombre_Act_Comp { get; set; }
        public string Descact { get; set; }
        public float Horas { get; set; }
        public float Costo_Hra { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaAct { get; set; }
        public string Vendedor { get; set; }
        public string status { get; set; }
        public int CveLN { get; set; }
        public string nombre_area { get; set; }
        public string Folio_Proyecto { get; set; }
        public string nombre_etapa { get; set; }
        public int AreaPM { get; set; }
        public string sistema { get; set; }
        public int Año_FechaAct { get; set; }
        public int Mes_FechaAct { get; set; }
        public int Dia_FechaAct { get; set; }
    }
}
