//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos.NAVINFO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ExplotacionActividades_SaiLine
    {
        public string CveAct_OPPM { get; set; }
        public string Folio { get; set; }
        public string DescOP { get; set; }
        public string Nom_Cliente { get; set; }
        public string EstatusOP { get; set; }
        public string CveAct { get; set; }
        public string UsResp { get; set; }
        public string RespAct { get; set; }
        public string Nom_Act_Comp { get; set; }
        public string DescAct { get; set; }
        public int Horas { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime fechaAct { get; set; }
        public string vendedor { get; set; }
        public string Status { get; set; }
        public string CveLN { get; set; }
        public string NombreLN { get; set; }
    }
}
