//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actividades()
        {
            this.documentos = new HashSet<documentos>();
        }
    
        public int id_actividad { get; set; }
        public Nullable<int> id_proyecto { get; set; }
        public Nullable<int> id_riesgo { get; set; }
        public string nombre { get; set; }
        public string usuario_resp { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public Nullable<System.DateTime> fecha_asignacion { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string comentarios_borrado { get; set; }
        public Nullable<System.DateTime> fecha_borrado { get; set; }
        public string usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string usuario_borrado { get; set; }
        public string empleado_resp { get; set; }
    
        public virtual proyectos proyectos { get; set; }
        public virtual riesgos riesgos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos> documentos { get; set; }
    }
}
