//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class bonds_types
    {
        public int id_bond_type { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> id_periodicity { get; set; }
        public Nullable<bool> amount_required { get; set; }
        public Nullable<bool> periodicity_required { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<bool> week_detail_required { get; set; }
        public Nullable<bool> folio_pmtracker_required { get; set; }
        public Nullable<bool> project_name_required { get; set; }
        public Nullable<bool> customer_name_required { get; set; }
        public Nullable<bool> number_hours_required { get; set; }
        public Nullable<bool> authorization_amount_capture { get; set; }
        public Nullable<bool> grid_requisitions_required { get; set; }
        public Nullable<bool> period_date_of_capture { get; set; }
        public Nullable<bool> period_date_to_capture { get; set; }
        public Nullable<bool> comments_authorization_required { get; set; }
        public Nullable<decimal> percentage_extra { get; set; }
        public Nullable<bool> month_select { get; set; }
        public Nullable<bool> files_required { get; set; }
    }
}
