//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class bons_automatic_types
    {
        public int IdBonds { get; set; }
        public string NameBonds { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Create_by { get; set; }
        public Nullable<bool> Enabled { get; set; }
    }
}
