//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos
    {
        public int id_documento { get; set; }
        public Nullable<int> id_documento_tipo { get; set; }
        public Nullable<int> id_proyecto { get; set; }
        public Nullable<int> id_actividad { get; set; }
        public string nombre { get; set; }
        public string contentType { get; set; }
        public string extension { get; set; }
        public string tamaño { get; set; }
        public bool publico { get; set; }
        public string path { get; set; }
        public System.DateTime fecha { get; set; }
        public string usuario { get; set; }
        public string usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string usuario_borrado { get; set; }
        public string comentarios_borrado { get; set; }
        public Nullable<System.DateTime> fecha_borrado { get; set; }
        public string comentarios { get; set; }
    
        public virtual actividades actividades { get; set; }
        public virtual documentos_tipos documentos_tipos { get; set; }
        public virtual proyectos proyectos { get; set; }
    }
}
