//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees_compensations
    {
        public int id_employee_compensations { get; set; }
        public int employee_number { get; set; }
        public int id_bond_type { get; set; }
        public decimal amount { get; set; }
        public Nullable<int> id_periodicity { get; set; }
        public Nullable<decimal> percentage_extra { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
    }
}
