//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class files_requests_bonds
    {
        public int id_file_request_bond { get; set; }
        public Nullable<int> id_request_bond { get; set; }
        public string path { get; set; }
        public string file_name { get; set; }
        public string content_type { get; set; }
        public Nullable<System.DateTime> date_attach { get; set; }
        public string login { get; set; }
    }
}
