//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_history
    {
        public int id_payment_history { get; set; }
        public Nullable<int> id_request_bond { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<int> id_comment_type_payment { get; set; }
        public string observations { get; set; }
        public string paid_by { get; set; }
    }
}
