//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodicity_ranges
    {
        public int id_periodicity_ranges { get; set; }
        public Nullable<int> id_periodicity { get; set; }
        public Nullable<int> mont_date_initial { get; set; }
        public Nullable<int> mont_date_finaly { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
    }
}
