//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissions_users_bonds_types
    {
        public string login { get; set; }
        public string permission_request_bond { get; set; }
        public string permision_authorization_bond { get; set; }
        public Nullable<bool> FiltroCC { get; set; }
        public Nullable<bool> Enabled { get; set; }
    }
}
