//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyectos_evaluaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proyectos_evaluaciones()
        {
            this.riesgos = new HashSet<riesgos>();
        }
    
        public int id_proyecto_evaluacion { get; set; }
        public int id_proyecto { get; set; }
        public System.DateTime fecha_evaluacion { get; set; }
        public Nullable<decimal> riesgo_costo { get; set; }
        public Nullable<short> riesgo_tiempo { get; set; }
        public Nullable<decimal> p_riesgo_costo { get; set; }
        public Nullable<decimal> p_riesgo_tiempo { get; set; }
        public System.DateTime fecha { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha_borrado { get; set; }
        public string usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string usuario_borrado { get; set; }
        public string comentarios_borrado { get; set; }
        public Nullable<decimal> riesgo_costo_mn { get; set; }
    
        public virtual proyectos proyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<riesgos> riesgos { get; set; }
    }
}
