//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyectos_minutas_pendientes
    {
        public int id_proyectominpen { get; set; }
        public decimal id_proyectomin { get; set; }
        public string descripcion { get; set; }
        public Nullable<byte> avance { get; set; }
        public string nombre { get; set; }
        public string usuario_resp { get; set; }
        public System.DateTime fecha_planeada { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string usuario_registro { get; set; }
        public string usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string usuario_borrado { get; set; }
        public Nullable<System.DateTime> fecha_borrado { get; set; }
        public string comentarios_borrado { get; set; }
    
        public virtual proyectos_minutas proyectos_minutas { get; set; }
    }
}
