//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyectos_minutas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proyectos_minutas()
        {
            this.proyectos_minutas_participantes = new HashSet<proyectos_minutas_participantes>();
            this.proyectos_minutas_pendientes = new HashSet<proyectos_minutas_pendientes>();
        }
    
        public decimal id_proyectomin { get; set; }
        public int id_proyecto { get; set; }
        public string asunto { get; set; }
        public System.DateTime fecha { get; set; }
        public string propósito { get; set; }
        public string resultados { get; set; }
        public string acuerdos { get; set; }
        public string lugar { get; set; }
        public bool enviada { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string usuario { get; set; }
        public string usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string usuario_borrado { get; set; }
        public string comentarios_borrado { get; set; }
        public Nullable<System.DateTime> fecha_borrado { get; set; }
    
        public virtual proyectos proyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyectos_minutas_participantes> proyectos_minutas_participantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proyectos_minutas_pendientes> proyectos_minutas_pendientes { get; set; }
    }
}
