//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Proyectos_ConnextEntities : DbContext
    {
        public Proyectos_ConnextEntities()
            : base("name=Proyectos_ConnextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actividades> actividades { get; set; }
        public virtual DbSet<documentos> documentos { get; set; }
        public virtual DbSet<documentos_tipos> documentos_tipos { get; set; }
        public virtual DbSet<proyectos> proyectos { get; set; }
        public virtual DbSet<proyectos_estatus> proyectos_estatus { get; set; }
        public virtual DbSet<proyectos_evaluaciones> proyectos_evaluaciones { get; set; }
        public virtual DbSet<proyectos_periodos> proyectos_periodos { get; set; }
        public virtual DbSet<proyectos_tecnologias> proyectos_tecnologias { get; set; }
        public virtual DbSet<riesgos> riesgos { get; set; }
        public virtual DbSet<riesgos_estatus> riesgos_estatus { get; set; }
        public virtual DbSet<riesgos_estrategia> riesgos_estrategia { get; set; }
        public virtual DbSet<riesgos_impacto_costo> riesgos_impacto_costo { get; set; }
        public virtual DbSet<riesgos_impacto_tiempo> riesgos_impacto_tiempo { get; set; }
        public virtual DbSet<riesgos_probabilidad> riesgos_probabilidad { get; set; }
    
        public virtual ObjectResult<sp_get_cped_Result> sp_get_cped(string pdocumento)
        {
            var pdocumentoParameter = pdocumento != null ?
                new ObjectParameter("pdocumento", pdocumento) :
                new ObjectParameter("pdocumento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_cped_Result>("sp_get_cped", pdocumentoParameter);
        }
    }
}
