//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyectos_historial_tecnologias
    {
        public decimal id_proyectoht { get; set; }
        public int id_proyecto { get; set; }
        public int id_proyecto_tecnologia { get; set; }
        public bool activo { get; set; }
    
        public virtual proyectos proyectos { get; set; }
        public virtual proyectos_tecnologias proyectos_tecnologias { get; set; }
    }
}
