//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests_bonds
    {
        public int id_request_bond { get; set; }
        public Nullable<int> employee_number { get; set; }
        public Nullable<decimal> authorization_amount { get; set; }
        public Nullable<decimal> amount_paid { get; set; }
        public Nullable<System.DateTime> period_date_of { get; set; }
        public Nullable<System.DateTime> period_date_to { get; set; }
        public Nullable<int> id_bond_type { get; set; }
        public Nullable<int> id_request_status { get; set; }
        public Nullable<decimal> number_hours { get; set; }
        public string folio_pmtracker { get; set; }
        public Nullable<int> week { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<System.DateTime> selected_date { get; set; }
        public string requisition_comments { get; set; }
        public string authorization_comments { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> id_comment_type_payment { get; set; }
        public string observations { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public string paid_by { get; set; }
        public Nullable<bool> pending_payment { get; set; }
        public Nullable<int> CC_Cargo { get; set; }
        public Nullable<int> CC_Empleado { get; set; }
        public Nullable<int> id_request_bond_Automatic { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public string Canceled_by { get; set; }
        public Nullable<System.DateTime> Cancellation_date { get; set; }
    }
}
