//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests_bonds_Automatic
    {
        public int Id_request_bond_automatic { get; set; }
        public Nullable<int> Employee_number { get; set; }
        public string Employee { get; set; }
        public Nullable<int> CC_Empleado { get; set; }
        public Nullable<int> IdBonds { get; set; }
        public string NameBonds { get; set; }
        public Nullable<int> Id_Periodicity { get; set; }
        public Nullable<int> Occurrences { get; set; }
        public Nullable<int> CC_Cargo { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public Nullable<System.DateTime> FinalDate { get; set; }
        public string observations { get; set; }
        public Nullable<int> PendingOccurrences { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> UpdateDelete { get; set; }
        public string UpdateDelete_By { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Update_by { get; set; }
        public string authorization_comments { get; set; }
        public Nullable<decimal> authorization_amount { get; set; }
        public string Authorization_by { get; set; }
        public Nullable<System.DateTime> AuthorizationDate { get; set; }
        public string Delete_comments { get; set; }
        public Nullable<System.DateTime> DeclinedDate { get; set; }
        public string Declined_By { get; set; }
        public string Declined_Comments { get; set; }
    }
}
