//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class riesgos_estrategia
    {
        public int id_riesgo_estrategia { get; set; }
        public string usuario { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
