//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class riesgos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public riesgos()
        {
            this.actividades = new HashSet<actividades>();
        }
    
        public int id_riesgo { get; set; }
        public int id_proyecto_evaluacion { get; set; }
        public int id_riesgos_estatus { get; set; }
        public string riesgo { get; set; }
        public int id_riesgo_probabilidad { get; set; }
        public decimal porc_probabilidad { get; set; }
        public int id_riesgo_impacto_costo { get; set; }
        public decimal porc_impcosto { get; set; }
        public int id_riesgo_impacto_tiempo { get; set; }
        public decimal porc_imptiempo { get; set; }
        public decimal riesgo_costo { get; set; }
        public decimal riesgo_tiempo { get; set; }
        public int id_riesgo_estrategia { get; set; }
        public Nullable<System.DateTime> fecha_borrado { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public string usuario { get; set; }
        public string usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public string usuario_borrado { get; set; }
        public string comentarios_borrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividades> actividades { get; set; }
        public virtual proyectos_evaluaciones proyectos_evaluaciones { get; set; }
        public virtual riesgos_estatus riesgos_estatus { get; set; }
        public virtual riesgos_estrategia riesgos_estrategia { get; set; }
        public virtual riesgos_impacto_costo riesgos_impacto_costo { get; set; }
        public virtual riesgos_impacto_tiempo riesgos_impacto_tiempo { get; set; }
        public virtual riesgos_probabilidad riesgos_probabilidad { get; set; }
    }
}
