//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_reporte_bonos
    {
        public Nullable<System.DateTime> fecha { get; set; }
        public string Login { get; set; }
        public string nombre { get; set; }
        public string cc { get; set; }
        public string Monto_Bono { get; set; }
        public string KPI_Individual { get; set; }
        public string KPI_Grupo { get; set; }
        public string C__Individual { get; set; }
        public string C__Grupal { get; set; }
        public string Bono { get; set; }
        public string C__Cump { get; set; }
        public string Total_Final { get; set; }
        public string C__Total_Final { get; set; }
        public string C__Preventa { get; set; }
        public string C__Implementación { get; set; }
        public string C__Soporte { get; set; }
        public string C__Proyectos { get; set; }
        public string Preventa { get; set; }
        public string Implementacion { get; set; }
        public string Soporte { get; set; }
        public string Proyecto { get; set; }
    }
}
