//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReplaceBoss
    {
        public int Id_CNSC_ReplaceBoss { get; set; }
        public string Login { get; set; }
        public string Replaced { get; set; }
        public string CC { get; set; }
        public Nullable<bool> BitActivo { get; set; }
        public Nullable<System.DateTime> FechaReg { get; set; }
        public string UsuarioReg { get; set; }
    }
}
